### ISSUE TITLE
PlanDefinition resource is not known by FRED

### ISSUE THREAD

**Issue by vadi2** [smart-on-fhir/fred#10]
Can't create or load [PlanDefinition](http://hl7.org/fhir/STU3/plandefinition.html) resources :confused:

**Comment by gotdan** [comment]
It's there for me - are you loading the version of FRED with the R3 profiles: http://docs.smarthealthit.org/fred/?profiles=.%2Fprofiles%2Fstu3.json ?

**Comment by vadi2** [comment]
Nope. Didn't even know about that link. Thanks!

**Comment by gotdan** [comment]
It's in the readme, but at some point I should probably add a selector to the ui :)
