### ISSUE TITLE
Cancel editing on Escape

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/fred#3]
Feature request: would be nice to cancel out of an edit box by hitting escape (dropping changes if any).

**Comment by gotdan** [comment]
It should be doing this already - is it not working?

**Comment by jmandel** [comment]
Not for me; I'll take a look at why on my setup. Probably a browser
extension I have installed of some such.

**Comment by gotdan** [comment]
Cool, let me know! I think the relevant code is https://github.com/smart-on-fhir/fred/blob/master/src/domain-resource/value-editor.cjsx#L34.

**Comment by jmandel** [comment]
My bad -- browser extension was eating my keystrokes.
