### ISSUE TITLE
Issue creating a 'bundled resource'

### ISSUE THREAD

**Issue by eneimi** [smart-on-fhir/fred#5]
The bundled resource feature doesn't appear to be working. I created a patient resource and tried adding an encounter or observation and it's a no show. Anything I'm doing wrong?

**Comment by gotdan** [comment]
Bundles are still a bit of a work in progress, but if you create a new resource (open resource > blank resource tab) with the "create in bundle" checkbox checked, you should get a new bundle in FRED. You can then add and remove resources using the button in the center for the bundle nav bar that appears. Let me know if this works for you!

**Comment by eneimi** [comment]
Yeah, that's what I tried. It allows me select 'Duplicate resource' and does create a duplicate of whatever resource I had initially selected, but does not respond when I select 'Insert resource'. So in essence I can create a bundle with multiple instances of the same resource, but cannot add more than one resource type to the bundle.

**Comment by gotdan** [comment]
Got it - it seems like recent changes may have broken that function. I'll look into it...

**Comment by gotdan** [comment]
It should be fixed in the latest commit and the version on the web - can you confirm?

**Comment by eneimi** [comment]
Great, I can confirm it works on the web.
I'll have to recompile my local implementation a little later to check that out as well. Or is it something I can edit myself (on my local machine)?

**Comment by gotdan** [comment]
Yes, the only change was this: https://github.com/smart-on-fhir/fred/commit/26512cb6bed5685b0d946ebe6fadb0d2180e9907
