### ISSUE TITLE
Extension with a ValueCodableConcept isn't build correclty

### ISSUE THREAD

**Issue by amyballard** [smart-on-fhir/fred#7]
I added an extension and selected value (CodeableConcept) as the value type and added code and display. The JSON returned when I Save and Close has the valueCodeableConcept as value[x].

"extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/us-core-race",
      "value[x]": {
        "coding": [
          {
            "code": "2106-3",
            "display": "White"
          }
        ]
      }
    }
  ]

**Comment by gotdan** [comment]
Are you using the latest version of FRED? It seems to work for me:

{
  "resourceType": "Patient",
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/us-core-race",
      "valueCodeableConcept": {
        "coding": [
          {
            "code": "2106-3",
            "display": "White"
          }
        ]
      }
    }
  ]
}

**Comment by amyballard** [comment]
Dan,

The first thing I did was grab the latest code and re-deploy. It looks like
it was the browser cache that got me. It's working now that I've cleared my
cache.

Thanks for the quick response.

Amy

**Comment by gotdan** [comment]
Sounds good - have a nice weekend!
