### ISSUE TITLE
STU3 support

### ISSUE THREAD

**Issue by vadi2** [smart-on-fhir/fred#8]
I was able to use FRED to pretty quickly prototype a Bundle of 10 interlinked resources in a day and a half - 450 lines of FHIR JSON in the end, I'm pretty happy with the result. Would it be possible to see STU3 snapshot support added? After the initial prototyping, I had to take my Bundle out and upgrade it to STU3 by hand, breaking roundtripping.

**Comment by gotdan** [comment]
I added STU3 support (FHIR 3.01) to FRED!

**Comment by jmandel** [comment]
:thumbsup:
